@REM This bat file has been generated by the IAR Embeddded Workbench
@REM C-SPY interactive debugger,as an aid to preparing a command
@REM line for running the cspybat command line utility with the
@REM appropriate settings.
@REM
@REM After making some adjustments to this file, you can launch cspybat
@REM by typing the name of this file followed by the name of the debug
@REM file (usually an ubrof file). Note that this file is generated
@REM every time a new debug session is initialized, so you may want to
@REM move or rename the file before making changes.
@REM
@REM Note: some command line arguments cannot be properly generated
@REM by this process. Specifically, the plugin which is responsible
@REM for the Terminal I/O window (and other C runtime functionality)
@REM comes in a special version for cspybat, and the name of that
@REM plugin dll is not known when generating this file. It resides in
@REM the $TOOLKIT_DIR$\bin folder and is usually called XXXbat.dll or
@REM XXXlibsupportbat.dll, where XXX is the name of the corresponding
@REM tool chain. Replace the '<libsupport_plugin>' parameter
@REM below with the appropriate file name. Other plugins loaded by
@REM C-SPY are usually not needed by, or will not work in, cspybat
@REM but they are listed at the end of this file for reference.


"H:\STM32\IAR\common\bin\cspybat" "H:\STM32\IAR\arm\bin\armproc.dll" "H:\STM32\IAR\arm\bin\armjlink.dll"  %1 --plugin "H:\STM32\IAR\arm\bin\<libsupport_plugin>" --flash_loader "H:\STM32\IAR\arm\config\flashloader\ST\FlashSTM32F10xxE.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "H:\STM32\IAR\arm\CONFIG\debugger\ST\iostm32f10xxe.ddf" "--semihosting" "--device=STM32F10xxE" "-d" "jlink" "--drv_communication=USB0" "--jlink_speed=auto" "--jlink_initial_speed=32" "--jlink_reset_strategy=0,0" "--jlink_interface=SWD" 


@REM Loaded plugins:
@REM    H:\STM32\IAR\arm\bin\armlibsupport.dll
@REM    H:\STM32\IAR\common\plugins\CodeCoverage\CodeCoverage.dll
@REM    H:\STM32\IAR\common\plugins\Profiling\Profiling.dll
@REM    H:\STM32\IAR\common\plugins\stack\stack.dll
@REM    H:\STM32\IAR\common\plugins\SymList\SymList.dll
